CREATE TABLE IF NOT EXISTS frames (
    id INTEGER NOT NULL PRIMARY KEY,
    tick_start INTEGER NOT NULL,
    tick_end INTEGER NOT NULL,
    progress REAL NOT NULL,
    is_processed INTEGER NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);