<!-- prettier-ignore -->
<template>
  <div class="flex flex-col px-3">
    <p class="text-md text-slate-500">
      These keys are used to access your cloud machine. They are generated by Commander and are used to secure your server
      from unwanted access while still allowing you to connect.
    </p>

    <label class="text-sm font-bold text-slate-800/70 mt-6 mb-2 block">
      Public Key
    </label>
    <CopyToClipboard
      ref="copyToClipboard"
      @click="highlightCopiedContent"
      :content="config.security.sshPublicKey"
      class="relative mb-3"
    >
      <input
        type="text"
        :value="config.security.sshPublicKey"
        class="bg-white py-3 pl-3 pr-8 border border-slate-300 rounded-md w-full pointer-events-none font-mono text-md"
        readonly
      />
      <div
        class="absolute right-8 top-1 w-10 bottom-1 bg-gradient-to-r from-transparent to-white pointer-events-auto"
      ></div>
      <div class="absolute right-4 top-1/2 -translate-y-1/2 pointer-events-none">
        <CopyIcon class="w-4 h-4" />
      </div>
      <template #copied>
        <div
          class="bg-white py-3 pl-3 pr-8 border border-slate-300 rounded-md w-full pointer-events-none overflow-hidden"
        >
          <span class="bg-blue-200 whitespace-nowrap w-full inline-block font-mono text-md">
            {{ config.security.sshPublicKey }}
          </span>
        </div>
        <div
          class="flex flex-row items-center absolute right-[1px] top-1/2 -translate-y-1/2 pointer-events-none bg-white pl-2 pr-[15px]"
        >
          <div
            class="absolute -left-8 w-8 top-0 bottom-0 bg-gradient-to-r from-transparent to-white pointer-events-auto"
          ></div>
          <span class="font-bold text-blue-800/60">Copied</span>
          <CopyIcon class="w-4 h-4 ml-3 text-blue-600" />
        </div>
      </template>
    </CopyToClipboard>

    <label class="text-sm font-bold text-slate-800/70 mt-3 mb-2 block">
      Private Key
    </label>
    <CopyToClipboard
      ref="copyToClipboard"
      @click="highlightCopiedContent"
      :content="config.security.sshPrivateKey"
      class="relative mb-3"
    >
      <textarea
        :style="{ height: privateKeyTextareaHeight }"
        class="bg-white py-3 pl-3 pr-8 border border-slate-300 rounded-md w-full pointer-events-none resize-none whitespace-pre overflow-hidden font-mono text-md focus:outline-none"
        readonly
      >{{ config.security.sshPrivateKey }}</textarea>
      <div
        class="absolute right-px rounded-r-md top-1 w-[72px] bottom-2 bg-gradient-to-r from-transparent to-[40px] to-white pointer-events-auto"
      ></div>
      <div class="absolute right-4 top-1/2 -translate-y-1/2 pointer-events-none">
        <CopyIcon class="w-4 h-4" />
      </div>
      <template #copied>
        <div
          ref="privateKeyTextareaShadow"
          class="bg-white py-3 pl-3 pr-8 border border-slate-300 rounded-md w-full pointer-events-none overflow-x-hidden"
        >
          <pre class="bg-blue-200 whitespace-pre w-full inline-block overflow-visible font-mono text-md">{{ config.security.sshPrivateKey }}</pre>
        </div>
        <div
          class="flex flex-row items-center absolute right-[1px] top-1 bottom-1 pointer-events-none bg-white pl-2 pr-[15px] rounded-r-md"
        >
          <div
            class="absolute -left-8 w-8 top-0 bottom-0 bg-gradient-to-r from-transparent to-white pointer-events-auto"
          ></div>
          <span class="font-bold text-blue-800/60">Copied</span>
          <CopyIcon class="w-4 h-4 ml-3 text-blue-600" />
        </div>
      </template>
    </CopyToClipboard>
  </div>
</template>

<script setup lang="ts">
import * as Vue from 'vue';
import { useConfig } from '../../stores/config';
import CopyToClipboard from '../../components/CopyToClipboard.vue';
import CopyIcon from '../../assets/copy.svg?component';

const config = useConfig();
const copyToClipboard = Vue.ref<typeof CopyToClipboard>();
const privateKeyTextareaShadow = Vue.ref<HTMLElement>();
const privateKeyTextareaHeight = Vue.ref('auto');

const emit = defineEmits(['close', 'goTo']);

function adjustTextareaHeight() {
  if (privateKeyTextareaShadow.value) {
    privateKeyTextareaHeight.value = privateKeyTextareaShadow.value.scrollHeight + 'px';
  } else {
    privateKeyTextareaHeight.value = 'auto';
  }
}

function highlightCopiedContent() {
  const parentWrapper = copyToClipboard.value?.$el as unknown as HTMLElement;
  if (!parentWrapper) return;
  let input: HTMLInputElement | HTMLTextAreaElement | null = null;
  input = parentWrapper.querySelector('input') as HTMLInputElement;
  if (!input) {
    input = parentWrapper.querySelector('textarea') as HTMLTextAreaElement | null;
  }
  if (input) {
    input.select();
  }
}

// Adjust textarea height when component mounts and when content changes
Vue.onMounted(() => {
  console.log('onMounted');
  adjustTextareaHeight();
  setTimeout(() => {
    adjustTextareaHeight();
  }, 1000);
});

Vue.watch(
  () => config.security.sshPrivateKey,
  () => {
    Vue.nextTick(() => {
      adjustTextareaHeight();
    });
  },
);
</script>
